/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.myACDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configuration Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getConfigurationType()
 * @model
 * @generated
 */
public interface ConfigurationType extends EObject
{
} // ConfigurationType
