/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.myACDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.Configuration#getAppName <em>App Name</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.Configuration#getOs <em>Os</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.Configuration#getAppServer <em>App Server</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.Configuration#getCommonParams <em>Common Params</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.Configuration#getConfigurations <em>Configurations</em>}</li>
 * </ul>
 *
 * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getConfiguration()
 * @model
 * @generated
 */
public interface Configuration extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>App Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>App Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>App Name</em>' attribute.
   * @see #setAppName(String)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getConfiguration_AppName()
   * @model
   * @generated
   */
  String getAppName();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.Configuration#getAppName <em>App Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>App Name</em>' attribute.
   * @see #getAppName()
   * @generated
   */
  void setAppName(String value);

  /**
   * Returns the value of the '<em><b>Os</b></em>' attribute.
   * The literals are from the enumeration {@link org.acac.demo.acdsl.myACDSL.SupportedOs}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Os</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Os</em>' attribute.
   * @see org.acac.demo.acdsl.myACDSL.SupportedOs
   * @see #setOs(SupportedOs)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getConfiguration_Os()
   * @model
   * @generated
   */
  SupportedOs getOs();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.Configuration#getOs <em>Os</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Os</em>' attribute.
   * @see org.acac.demo.acdsl.myACDSL.SupportedOs
   * @see #getOs()
   * @generated
   */
  void setOs(SupportedOs value);

  /**
   * Returns the value of the '<em><b>App Server</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>App Server</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>App Server</em>' containment reference.
   * @see #setAppServer(AppServerInfo)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getConfiguration_AppServer()
   * @model containment="true"
   * @generated
   */
  AppServerInfo getAppServer();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.Configuration#getAppServer <em>App Server</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>App Server</em>' containment reference.
   * @see #getAppServer()
   * @generated
   */
  void setAppServer(AppServerInfo value);

  /**
   * Returns the value of the '<em><b>Common Params</b></em>' containment reference list.
   * The list contents are of type {@link org.acac.demo.acdsl.myACDSL.CommonParam}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Common Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Common Params</em>' containment reference list.
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getConfiguration_CommonParams()
   * @model containment="true"
   * @generated
   */
  EList<CommonParam> getCommonParams();

  /**
   * Returns the value of the '<em><b>Configurations</b></em>' containment reference list.
   * The list contents are of type {@link org.acac.demo.acdsl.myACDSL.ConfigurationType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Configurations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configurations</em>' containment reference list.
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getConfiguration_Configurations()
   * @model containment="true"
   * @generated
   */
  EList<ConfigurationType> getConfigurations();

} // Configuration
