/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.myACDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Source</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.DataSource#getScope <em>Scope</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.DataSource#getDataSourceName <em>Data Source Name</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.DataSource#getJndiName <em>Jndi Name</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.DataSource#getJdbcProviderName <em>Jdbc Provider Name</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.DataSource#getDataSourceUrl <em>Data Source Url</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.DataSource#getComponentManagedAuthenticationAlias <em>Component Managed Authentication Alias</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.DataSource#getMappingConfigurationAlias <em>Mapping Configuration Alias</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.DataSource#getContainerMmanagedAuthenticationAlias <em>Container Mmanaged Authentication Alias</em>}</li>
 * </ul>
 *
 * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getDataSource()
 * @model
 * @generated
 */
public interface DataSource extends ConfigurationType
{
  /**
   * Returns the value of the '<em><b>Scope</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scope</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scope</em>' reference.
   * @see #setScope(CommonParam)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getDataSource_Scope()
   * @model
   * @generated
   */
  CommonParam getScope();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.DataSource#getScope <em>Scope</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scope</em>' reference.
   * @see #getScope()
   * @generated
   */
  void setScope(CommonParam value);

  /**
   * Returns the value of the '<em><b>Data Source Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data Source Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Source Name</em>' attribute.
   * @see #setDataSourceName(String)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getDataSource_DataSourceName()
   * @model
   * @generated
   */
  String getDataSourceName();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.DataSource#getDataSourceName <em>Data Source Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Source Name</em>' attribute.
   * @see #getDataSourceName()
   * @generated
   */
  void setDataSourceName(String value);

  /**
   * Returns the value of the '<em><b>Jndi Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Jndi Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jndi Name</em>' attribute.
   * @see #setJndiName(String)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getDataSource_JndiName()
   * @model
   * @generated
   */
  String getJndiName();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.DataSource#getJndiName <em>Jndi Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Jndi Name</em>' attribute.
   * @see #getJndiName()
   * @generated
   */
  void setJndiName(String value);

  /**
   * Returns the value of the '<em><b>Jdbc Provider Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Jdbc Provider Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jdbc Provider Name</em>' attribute.
   * @see #setJdbcProviderName(String)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getDataSource_JdbcProviderName()
   * @model
   * @generated
   */
  String getJdbcProviderName();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.DataSource#getJdbcProviderName <em>Jdbc Provider Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Jdbc Provider Name</em>' attribute.
   * @see #getJdbcProviderName()
   * @generated
   */
  void setJdbcProviderName(String value);

  /**
   * Returns the value of the '<em><b>Data Source Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data Source Url</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Source Url</em>' attribute.
   * @see #setDataSourceUrl(String)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getDataSource_DataSourceUrl()
   * @model
   * @generated
   */
  String getDataSourceUrl();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.DataSource#getDataSourceUrl <em>Data Source Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Source Url</em>' attribute.
   * @see #getDataSourceUrl()
   * @generated
   */
  void setDataSourceUrl(String value);

  /**
   * Returns the value of the '<em><b>Component Managed Authentication Alias</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component Managed Authentication Alias</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component Managed Authentication Alias</em>' reference.
   * @see #setComponentManagedAuthenticationAlias(CommonParam)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getDataSource_ComponentManagedAuthenticationAlias()
   * @model
   * @generated
   */
  CommonParam getComponentManagedAuthenticationAlias();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.DataSource#getComponentManagedAuthenticationAlias <em>Component Managed Authentication Alias</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component Managed Authentication Alias</em>' reference.
   * @see #getComponentManagedAuthenticationAlias()
   * @generated
   */
  void setComponentManagedAuthenticationAlias(CommonParam value);

  /**
   * Returns the value of the '<em><b>Mapping Configuration Alias</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mapping Configuration Alias</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mapping Configuration Alias</em>' reference.
   * @see #setMappingConfigurationAlias(CommonParam)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getDataSource_MappingConfigurationAlias()
   * @model
   * @generated
   */
  CommonParam getMappingConfigurationAlias();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.DataSource#getMappingConfigurationAlias <em>Mapping Configuration Alias</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mapping Configuration Alias</em>' reference.
   * @see #getMappingConfigurationAlias()
   * @generated
   */
  void setMappingConfigurationAlias(CommonParam value);

  /**
   * Returns the value of the '<em><b>Container Mmanaged Authentication Alias</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Container Mmanaged Authentication Alias</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Container Mmanaged Authentication Alias</em>' reference.
   * @see #setContainerMmanagedAuthenticationAlias(CommonParam)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getDataSource_ContainerMmanagedAuthenticationAlias()
   * @model
   * @generated
   */
  CommonParam getContainerMmanagedAuthenticationAlias();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.DataSource#getContainerMmanagedAuthenticationAlias <em>Container Mmanaged Authentication Alias</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Container Mmanaged Authentication Alias</em>' reference.
   * @see #getContainerMmanagedAuthenticationAlias()
   * @generated
   */
  void setContainerMmanagedAuthenticationAlias(CommonParam value);

} // DataSource
