/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.myACDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Deployment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.Deployment#getAppOp <em>App Op</em>}</li>
 * </ul>
 *
 * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getDeployment()
 * @model
 * @generated
 */
public interface Deployment extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>App Op</b></em>' attribute list.
   * The list contents are of type {@link org.acac.demo.acdsl.myACDSL.DeploymentOp}.
   * The literals are from the enumeration {@link org.acac.demo.acdsl.myACDSL.DeploymentOp}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>App Op</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>App Op</em>' attribute list.
   * @see org.acac.demo.acdsl.myACDSL.DeploymentOp
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getDeployment_AppOp()
   * @model unique="false"
   * @generated
   */
  EList<DeploymentOp> getAppOp();

} // Deployment
