/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.myACDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JAAS Alias</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.JAASAlias#getAlias <em>Alias</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.JAASAlias#getUsername <em>Username</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.JAASAlias#getPassword <em>Password</em>}</li>
 * </ul>
 *
 * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getJAASAlias()
 * @model
 * @generated
 */
public interface JAASAlias extends ConfigurationType
{
  /**
   * Returns the value of the '<em><b>Alias</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alias</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' reference.
   * @see #setAlias(CommonParam)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getJAASAlias_Alias()
   * @model
   * @generated
   */
  CommonParam getAlias();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.JAASAlias#getAlias <em>Alias</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alias</em>' reference.
   * @see #getAlias()
   * @generated
   */
  void setAlias(CommonParam value);

  /**
   * Returns the value of the '<em><b>Username</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Username</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Username</em>' attribute.
   * @see #setUsername(String)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getJAASAlias_Username()
   * @model
   * @generated
   */
  String getUsername();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.JAASAlias#getUsername <em>Username</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Username</em>' attribute.
   * @see #getUsername()
   * @generated
   */
  void setUsername(String value);

  /**
   * Returns the value of the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Password</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Password</em>' attribute.
   * @see #setPassword(String)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getJAASAlias_Password()
   * @model
   * @generated
   */
  String getPassword();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.JAASAlias#getPassword <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Password</em>' attribute.
   * @see #getPassword()
   * @generated
   */
  void setPassword(String value);

} // JAASAlias
