/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.myACDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Jdbc Provider</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getScope <em>Scope</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getDatabaseType <em>Database Type</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getProviderType <em>Provider Type</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getImplementationType <em>Implementation Type</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getName <em>Name</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getDescription <em>Description</em>}</li>
 *   <li>{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getClasspath <em>Classpath</em>}</li>
 * </ul>
 *
 * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getJdbcProvider()
 * @model
 * @generated
 */
public interface JdbcProvider extends ConfigurationType
{
  /**
   * Returns the value of the '<em><b>Scope</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scope</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scope</em>' reference.
   * @see #setScope(CommonParam)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getJdbcProvider_Scope()
   * @model
   * @generated
   */
  CommonParam getScope();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getScope <em>Scope</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scope</em>' reference.
   * @see #getScope()
   * @generated
   */
  void setScope(CommonParam value);

  /**
   * Returns the value of the '<em><b>Database Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Database Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Database Type</em>' attribute.
   * @see #setDatabaseType(String)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getJdbcProvider_DatabaseType()
   * @model
   * @generated
   */
  String getDatabaseType();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getDatabaseType <em>Database Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Database Type</em>' attribute.
   * @see #getDatabaseType()
   * @generated
   */
  void setDatabaseType(String value);

  /**
   * Returns the value of the '<em><b>Provider Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Provider Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Provider Type</em>' attribute.
   * @see #setProviderType(String)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getJdbcProvider_ProviderType()
   * @model
   * @generated
   */
  String getProviderType();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getProviderType <em>Provider Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Provider Type</em>' attribute.
   * @see #getProviderType()
   * @generated
   */
  void setProviderType(String value);

  /**
   * Returns the value of the '<em><b>Implementation Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Implementation Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Implementation Type</em>' attribute.
   * @see #setImplementationType(String)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getJdbcProvider_ImplementationType()
   * @model
   * @generated
   */
  String getImplementationType();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getImplementationType <em>Implementation Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Implementation Type</em>' attribute.
   * @see #getImplementationType()
   * @generated
   */
  void setImplementationType(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getJdbcProvider_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getJdbcProvider_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Classpath</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Classpath</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classpath</em>' reference.
   * @see #setClasspath(CommonParam)
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#getJdbcProvider_Classpath()
   * @model
   * @generated
   */
  CommonParam getClasspath();

  /**
   * Sets the value of the '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getClasspath <em>Classpath</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Classpath</em>' reference.
   * @see #getClasspath()
   * @generated
   */
  void setClasspath(CommonParam value);

} // JdbcProvider
