/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.myACDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.acac.demo.acdsl.myACDSL.MyACDSLFactory
 * @model kind="package"
 * @generated
 */
public interface MyACDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myACDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.acac.org/demo/acdsl/MyACDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myACDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyACDSLPackage eINSTANCE = org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.impl.ModelImpl
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.impl.AbstractElementImpl
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.impl.ConfigurationImpl <em>Configuration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.impl.ConfigurationImpl
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getConfiguration()
   * @generated
   */
  int CONFIGURATION = 2;

  /**
   * The feature id for the '<em><b>App Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__APP_NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Os</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__OS = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>App Server</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__APP_SERVER = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Common Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__COMMON_PARAMS = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Configurations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__CONFIGURATIONS = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Configuration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.impl.DeploymentImpl <em>Deployment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.impl.DeploymentImpl
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getDeployment()
   * @generated
   */
  int DEPLOYMENT = 3;

  /**
   * The feature id for the '<em><b>App Op</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT__APP_OP = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Deployment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.impl.OperationImpl
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 4;

  /**
   * The feature id for the '<em><b>Server Op</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__SERVER_OP = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.impl.AppServerInfoImpl <em>App Server Info</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.impl.AppServerInfoImpl
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getAppServerInfo()
   * @generated
   */
  int APP_SERVER_INFO = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APP_SERVER_INFO__NAME = 0;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APP_SERVER_INFO__VERSION = 1;

  /**
   * The number of structural features of the '<em>App Server Info</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APP_SERVER_INFO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.impl.CommonParamImpl <em>Common Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.impl.CommonParamImpl
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getCommonParam()
   * @generated
   */
  int COMMON_PARAM = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMON_PARAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMON_PARAM__VALUE = 1;

  /**
   * The number of structural features of the '<em>Common Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMON_PARAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.impl.ConfigurationTypeImpl <em>Configuration Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.impl.ConfigurationTypeImpl
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getConfigurationType()
   * @generated
   */
  int CONFIGURATION_TYPE = 7;

  /**
   * The number of structural features of the '<em>Configuration Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.impl.DataSourceImpl <em>Data Source</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.impl.DataSourceImpl
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getDataSource()
   * @generated
   */
  int DATA_SOURCE = 8;

  /**
   * The feature id for the '<em><b>Scope</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_SOURCE__SCOPE = CONFIGURATION_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Data Source Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_SOURCE__DATA_SOURCE_NAME = CONFIGURATION_TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Jndi Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_SOURCE__JNDI_NAME = CONFIGURATION_TYPE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Jdbc Provider Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_SOURCE__JDBC_PROVIDER_NAME = CONFIGURATION_TYPE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Data Source Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_SOURCE__DATA_SOURCE_URL = CONFIGURATION_TYPE_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Component Managed Authentication Alias</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_SOURCE__COMPONENT_MANAGED_AUTHENTICATION_ALIAS = CONFIGURATION_TYPE_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Mapping Configuration Alias</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_SOURCE__MAPPING_CONFIGURATION_ALIAS = CONFIGURATION_TYPE_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Container Mmanaged Authentication Alias</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_SOURCE__CONTAINER_MMANAGED_AUTHENTICATION_ALIAS = CONFIGURATION_TYPE_FEATURE_COUNT + 7;

  /**
   * The number of structural features of the '<em>Data Source</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_SOURCE_FEATURE_COUNT = CONFIGURATION_TYPE_FEATURE_COUNT + 8;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.impl.JdbcProviderImpl <em>Jdbc Provider</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.impl.JdbcProviderImpl
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getJdbcProvider()
   * @generated
   */
  int JDBC_PROVIDER = 9;

  /**
   * The feature id for the '<em><b>Scope</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JDBC_PROVIDER__SCOPE = CONFIGURATION_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Database Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JDBC_PROVIDER__DATABASE_TYPE = CONFIGURATION_TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Provider Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JDBC_PROVIDER__PROVIDER_TYPE = CONFIGURATION_TYPE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Implementation Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JDBC_PROVIDER__IMPLEMENTATION_TYPE = CONFIGURATION_TYPE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JDBC_PROVIDER__NAME = CONFIGURATION_TYPE_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JDBC_PROVIDER__DESCRIPTION = CONFIGURATION_TYPE_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Classpath</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JDBC_PROVIDER__CLASSPATH = CONFIGURATION_TYPE_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>Jdbc Provider</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JDBC_PROVIDER_FEATURE_COUNT = CONFIGURATION_TYPE_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.impl.JAASAliasImpl <em>JAAS Alias</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.impl.JAASAliasImpl
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getJAASAlias()
   * @generated
   */
  int JAAS_ALIAS = 10;

  /**
   * The feature id for the '<em><b>Alias</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAAS_ALIAS__ALIAS = CONFIGURATION_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Username</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAAS_ALIAS__USERNAME = CONFIGURATION_TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAAS_ALIAS__PASSWORD = CONFIGURATION_TYPE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>JAAS Alias</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAAS_ALIAS_FEATURE_COUNT = CONFIGURATION_TYPE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.impl.ServerJvmSettingImpl <em>Server Jvm Setting</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.impl.ServerJvmSettingImpl
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getServerJvmSetting()
   * @generated
   */
  int SERVER_JVM_SETTING = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_JVM_SETTING__NAME = CONFIGURATION_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_JVM_SETTING__VALUE = CONFIGURATION_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Server Jvm Setting</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_JVM_SETTING_FEATURE_COUNT = CONFIGURATION_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.SupportedContainer <em>Supported Container</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.SupportedContainer
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getSupportedContainer()
   * @generated
   */
  int SUPPORTED_CONTAINER = 12;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.SupportedContainerOperations <em>Supported Container Operations</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.SupportedContainerOperations
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getSupportedContainerOperations()
   * @generated
   */
  int SUPPORTED_CONTAINER_OPERATIONS = 13;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.SupportedOs <em>Supported Os</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.SupportedOs
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getSupportedOs()
   * @generated
   */
  int SUPPORTED_OS = 14;

  /**
   * The meta object id for the '{@link org.acac.demo.acdsl.myACDSL.DeploymentOp <em>Deployment Op</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.acac.demo.acdsl.myACDSL.DeploymentOp
   * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getDeploymentOp()
   * @generated
   */
  int DEPLOYMENT_OP = 15;


  /**
   * Returns the meta object for class '{@link org.acac.demo.acdsl.myACDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.acac.demo.acdsl.myACDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.acac.demo.acdsl.myACDSL.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.acac.demo.acdsl.myACDSL.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.acac.demo.acdsl.myACDSL.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see org.acac.demo.acdsl.myACDSL.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link org.acac.demo.acdsl.myACDSL.Configuration <em>Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Configuration</em>'.
   * @see org.acac.demo.acdsl.myACDSL.Configuration
   * @generated
   */
  EClass getConfiguration();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.Configuration#getAppName <em>App Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>App Name</em>'.
   * @see org.acac.demo.acdsl.myACDSL.Configuration#getAppName()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_AppName();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.Configuration#getOs <em>Os</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Os</em>'.
   * @see org.acac.demo.acdsl.myACDSL.Configuration#getOs()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Os();

  /**
   * Returns the meta object for the containment reference '{@link org.acac.demo.acdsl.myACDSL.Configuration#getAppServer <em>App Server</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>App Server</em>'.
   * @see org.acac.demo.acdsl.myACDSL.Configuration#getAppServer()
   * @see #getConfiguration()
   * @generated
   */
  EReference getConfiguration_AppServer();

  /**
   * Returns the meta object for the containment reference list '{@link org.acac.demo.acdsl.myACDSL.Configuration#getCommonParams <em>Common Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Common Params</em>'.
   * @see org.acac.demo.acdsl.myACDSL.Configuration#getCommonParams()
   * @see #getConfiguration()
   * @generated
   */
  EReference getConfiguration_CommonParams();

  /**
   * Returns the meta object for the containment reference list '{@link org.acac.demo.acdsl.myACDSL.Configuration#getConfigurations <em>Configurations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Configurations</em>'.
   * @see org.acac.demo.acdsl.myACDSL.Configuration#getConfigurations()
   * @see #getConfiguration()
   * @generated
   */
  EReference getConfiguration_Configurations();

  /**
   * Returns the meta object for class '{@link org.acac.demo.acdsl.myACDSL.Deployment <em>Deployment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Deployment</em>'.
   * @see org.acac.demo.acdsl.myACDSL.Deployment
   * @generated
   */
  EClass getDeployment();

  /**
   * Returns the meta object for the attribute list '{@link org.acac.demo.acdsl.myACDSL.Deployment#getAppOp <em>App Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>App Op</em>'.
   * @see org.acac.demo.acdsl.myACDSL.Deployment#getAppOp()
   * @see #getDeployment()
   * @generated
   */
  EAttribute getDeployment_AppOp();

  /**
   * Returns the meta object for class '{@link org.acac.demo.acdsl.myACDSL.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.acac.demo.acdsl.myACDSL.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the attribute list '{@link org.acac.demo.acdsl.myACDSL.Operation#getServerOp <em>Server Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Server Op</em>'.
   * @see org.acac.demo.acdsl.myACDSL.Operation#getServerOp()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_ServerOp();

  /**
   * Returns the meta object for class '{@link org.acac.demo.acdsl.myACDSL.AppServerInfo <em>App Server Info</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>App Server Info</em>'.
   * @see org.acac.demo.acdsl.myACDSL.AppServerInfo
   * @generated
   */
  EClass getAppServerInfo();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.AppServerInfo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.acac.demo.acdsl.myACDSL.AppServerInfo#getName()
   * @see #getAppServerInfo()
   * @generated
   */
  EAttribute getAppServerInfo_Name();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.AppServerInfo#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see org.acac.demo.acdsl.myACDSL.AppServerInfo#getVersion()
   * @see #getAppServerInfo()
   * @generated
   */
  EAttribute getAppServerInfo_Version();

  /**
   * Returns the meta object for class '{@link org.acac.demo.acdsl.myACDSL.CommonParam <em>Common Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Common Param</em>'.
   * @see org.acac.demo.acdsl.myACDSL.CommonParam
   * @generated
   */
  EClass getCommonParam();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.CommonParam#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.acac.demo.acdsl.myACDSL.CommonParam#getName()
   * @see #getCommonParam()
   * @generated
   */
  EAttribute getCommonParam_Name();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.CommonParam#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.acac.demo.acdsl.myACDSL.CommonParam#getValue()
   * @see #getCommonParam()
   * @generated
   */
  EAttribute getCommonParam_Value();

  /**
   * Returns the meta object for class '{@link org.acac.demo.acdsl.myACDSL.ConfigurationType <em>Configuration Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Configuration Type</em>'.
   * @see org.acac.demo.acdsl.myACDSL.ConfigurationType
   * @generated
   */
  EClass getConfigurationType();

  /**
   * Returns the meta object for class '{@link org.acac.demo.acdsl.myACDSL.DataSource <em>Data Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Source</em>'.
   * @see org.acac.demo.acdsl.myACDSL.DataSource
   * @generated
   */
  EClass getDataSource();

  /**
   * Returns the meta object for the reference '{@link org.acac.demo.acdsl.myACDSL.DataSource#getScope <em>Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Scope</em>'.
   * @see org.acac.demo.acdsl.myACDSL.DataSource#getScope()
   * @see #getDataSource()
   * @generated
   */
  EReference getDataSource_Scope();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.DataSource#getDataSourceName <em>Data Source Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Data Source Name</em>'.
   * @see org.acac.demo.acdsl.myACDSL.DataSource#getDataSourceName()
   * @see #getDataSource()
   * @generated
   */
  EAttribute getDataSource_DataSourceName();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.DataSource#getJndiName <em>Jndi Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Jndi Name</em>'.
   * @see org.acac.demo.acdsl.myACDSL.DataSource#getJndiName()
   * @see #getDataSource()
   * @generated
   */
  EAttribute getDataSource_JndiName();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.DataSource#getJdbcProviderName <em>Jdbc Provider Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Jdbc Provider Name</em>'.
   * @see org.acac.demo.acdsl.myACDSL.DataSource#getJdbcProviderName()
   * @see #getDataSource()
   * @generated
   */
  EAttribute getDataSource_JdbcProviderName();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.DataSource#getDataSourceUrl <em>Data Source Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Data Source Url</em>'.
   * @see org.acac.demo.acdsl.myACDSL.DataSource#getDataSourceUrl()
   * @see #getDataSource()
   * @generated
   */
  EAttribute getDataSource_DataSourceUrl();

  /**
   * Returns the meta object for the reference '{@link org.acac.demo.acdsl.myACDSL.DataSource#getComponentManagedAuthenticationAlias <em>Component Managed Authentication Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Component Managed Authentication Alias</em>'.
   * @see org.acac.demo.acdsl.myACDSL.DataSource#getComponentManagedAuthenticationAlias()
   * @see #getDataSource()
   * @generated
   */
  EReference getDataSource_ComponentManagedAuthenticationAlias();

  /**
   * Returns the meta object for the reference '{@link org.acac.demo.acdsl.myACDSL.DataSource#getMappingConfigurationAlias <em>Mapping Configuration Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Mapping Configuration Alias</em>'.
   * @see org.acac.demo.acdsl.myACDSL.DataSource#getMappingConfigurationAlias()
   * @see #getDataSource()
   * @generated
   */
  EReference getDataSource_MappingConfigurationAlias();

  /**
   * Returns the meta object for the reference '{@link org.acac.demo.acdsl.myACDSL.DataSource#getContainerMmanagedAuthenticationAlias <em>Container Mmanaged Authentication Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Container Mmanaged Authentication Alias</em>'.
   * @see org.acac.demo.acdsl.myACDSL.DataSource#getContainerMmanagedAuthenticationAlias()
   * @see #getDataSource()
   * @generated
   */
  EReference getDataSource_ContainerMmanagedAuthenticationAlias();

  /**
   * Returns the meta object for class '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider <em>Jdbc Provider</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Jdbc Provider</em>'.
   * @see org.acac.demo.acdsl.myACDSL.JdbcProvider
   * @generated
   */
  EClass getJdbcProvider();

  /**
   * Returns the meta object for the reference '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getScope <em>Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Scope</em>'.
   * @see org.acac.demo.acdsl.myACDSL.JdbcProvider#getScope()
   * @see #getJdbcProvider()
   * @generated
   */
  EReference getJdbcProvider_Scope();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getDatabaseType <em>Database Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Database Type</em>'.
   * @see org.acac.demo.acdsl.myACDSL.JdbcProvider#getDatabaseType()
   * @see #getJdbcProvider()
   * @generated
   */
  EAttribute getJdbcProvider_DatabaseType();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getProviderType <em>Provider Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Provider Type</em>'.
   * @see org.acac.demo.acdsl.myACDSL.JdbcProvider#getProviderType()
   * @see #getJdbcProvider()
   * @generated
   */
  EAttribute getJdbcProvider_ProviderType();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getImplementationType <em>Implementation Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Implementation Type</em>'.
   * @see org.acac.demo.acdsl.myACDSL.JdbcProvider#getImplementationType()
   * @see #getJdbcProvider()
   * @generated
   */
  EAttribute getJdbcProvider_ImplementationType();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.acac.demo.acdsl.myACDSL.JdbcProvider#getName()
   * @see #getJdbcProvider()
   * @generated
   */
  EAttribute getJdbcProvider_Name();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.acac.demo.acdsl.myACDSL.JdbcProvider#getDescription()
   * @see #getJdbcProvider()
   * @generated
   */
  EAttribute getJdbcProvider_Description();

  /**
   * Returns the meta object for the reference '{@link org.acac.demo.acdsl.myACDSL.JdbcProvider#getClasspath <em>Classpath</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Classpath</em>'.
   * @see org.acac.demo.acdsl.myACDSL.JdbcProvider#getClasspath()
   * @see #getJdbcProvider()
   * @generated
   */
  EReference getJdbcProvider_Classpath();

  /**
   * Returns the meta object for class '{@link org.acac.demo.acdsl.myACDSL.JAASAlias <em>JAAS Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JAAS Alias</em>'.
   * @see org.acac.demo.acdsl.myACDSL.JAASAlias
   * @generated
   */
  EClass getJAASAlias();

  /**
   * Returns the meta object for the reference '{@link org.acac.demo.acdsl.myACDSL.JAASAlias#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Alias</em>'.
   * @see org.acac.demo.acdsl.myACDSL.JAASAlias#getAlias()
   * @see #getJAASAlias()
   * @generated
   */
  EReference getJAASAlias_Alias();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.JAASAlias#getUsername <em>Username</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Username</em>'.
   * @see org.acac.demo.acdsl.myACDSL.JAASAlias#getUsername()
   * @see #getJAASAlias()
   * @generated
   */
  EAttribute getJAASAlias_Username();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.JAASAlias#getPassword <em>Password</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Password</em>'.
   * @see org.acac.demo.acdsl.myACDSL.JAASAlias#getPassword()
   * @see #getJAASAlias()
   * @generated
   */
  EAttribute getJAASAlias_Password();

  /**
   * Returns the meta object for class '{@link org.acac.demo.acdsl.myACDSL.ServerJvmSetting <em>Server Jvm Setting</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Server Jvm Setting</em>'.
   * @see org.acac.demo.acdsl.myACDSL.ServerJvmSetting
   * @generated
   */
  EClass getServerJvmSetting();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.ServerJvmSetting#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.acac.demo.acdsl.myACDSL.ServerJvmSetting#getName()
   * @see #getServerJvmSetting()
   * @generated
   */
  EAttribute getServerJvmSetting_Name();

  /**
   * Returns the meta object for the attribute '{@link org.acac.demo.acdsl.myACDSL.ServerJvmSetting#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.acac.demo.acdsl.myACDSL.ServerJvmSetting#getValue()
   * @see #getServerJvmSetting()
   * @generated
   */
  EAttribute getServerJvmSetting_Value();

  /**
   * Returns the meta object for enum '{@link org.acac.demo.acdsl.myACDSL.SupportedContainer <em>Supported Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Supported Container</em>'.
   * @see org.acac.demo.acdsl.myACDSL.SupportedContainer
   * @generated
   */
  EEnum getSupportedContainer();

  /**
   * Returns the meta object for enum '{@link org.acac.demo.acdsl.myACDSL.SupportedContainerOperations <em>Supported Container Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Supported Container Operations</em>'.
   * @see org.acac.demo.acdsl.myACDSL.SupportedContainerOperations
   * @generated
   */
  EEnum getSupportedContainerOperations();

  /**
   * Returns the meta object for enum '{@link org.acac.demo.acdsl.myACDSL.SupportedOs <em>Supported Os</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Supported Os</em>'.
   * @see org.acac.demo.acdsl.myACDSL.SupportedOs
   * @generated
   */
  EEnum getSupportedOs();

  /**
   * Returns the meta object for enum '{@link org.acac.demo.acdsl.myACDSL.DeploymentOp <em>Deployment Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Deployment Op</em>'.
   * @see org.acac.demo.acdsl.myACDSL.DeploymentOp
   * @generated
   */
  EEnum getDeploymentOp();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyACDSLFactory getMyACDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.impl.ModelImpl
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.impl.AbstractElementImpl
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.impl.ConfigurationImpl <em>Configuration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.impl.ConfigurationImpl
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getConfiguration()
     * @generated
     */
    EClass CONFIGURATION = eINSTANCE.getConfiguration();

    /**
     * The meta object literal for the '<em><b>App Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__APP_NAME = eINSTANCE.getConfiguration_AppName();

    /**
     * The meta object literal for the '<em><b>Os</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__OS = eINSTANCE.getConfiguration_Os();

    /**
     * The meta object literal for the '<em><b>App Server</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATION__APP_SERVER = eINSTANCE.getConfiguration_AppServer();

    /**
     * The meta object literal for the '<em><b>Common Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATION__COMMON_PARAMS = eINSTANCE.getConfiguration_CommonParams();

    /**
     * The meta object literal for the '<em><b>Configurations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATION__CONFIGURATIONS = eINSTANCE.getConfiguration_Configurations();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.impl.DeploymentImpl <em>Deployment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.impl.DeploymentImpl
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getDeployment()
     * @generated
     */
    EClass DEPLOYMENT = eINSTANCE.getDeployment();

    /**
     * The meta object literal for the '<em><b>App Op</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPLOYMENT__APP_OP = eINSTANCE.getDeployment_AppOp();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.impl.OperationImpl
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Server Op</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__SERVER_OP = eINSTANCE.getOperation_ServerOp();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.impl.AppServerInfoImpl <em>App Server Info</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.impl.AppServerInfoImpl
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getAppServerInfo()
     * @generated
     */
    EClass APP_SERVER_INFO = eINSTANCE.getAppServerInfo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APP_SERVER_INFO__NAME = eINSTANCE.getAppServerInfo_Name();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APP_SERVER_INFO__VERSION = eINSTANCE.getAppServerInfo_Version();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.impl.CommonParamImpl <em>Common Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.impl.CommonParamImpl
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getCommonParam()
     * @generated
     */
    EClass COMMON_PARAM = eINSTANCE.getCommonParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMON_PARAM__NAME = eINSTANCE.getCommonParam_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMON_PARAM__VALUE = eINSTANCE.getCommonParam_Value();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.impl.ConfigurationTypeImpl <em>Configuration Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.impl.ConfigurationTypeImpl
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getConfigurationType()
     * @generated
     */
    EClass CONFIGURATION_TYPE = eINSTANCE.getConfigurationType();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.impl.DataSourceImpl <em>Data Source</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.impl.DataSourceImpl
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getDataSource()
     * @generated
     */
    EClass DATA_SOURCE = eINSTANCE.getDataSource();

    /**
     * The meta object literal for the '<em><b>Scope</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_SOURCE__SCOPE = eINSTANCE.getDataSource_Scope();

    /**
     * The meta object literal for the '<em><b>Data Source Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_SOURCE__DATA_SOURCE_NAME = eINSTANCE.getDataSource_DataSourceName();

    /**
     * The meta object literal for the '<em><b>Jndi Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_SOURCE__JNDI_NAME = eINSTANCE.getDataSource_JndiName();

    /**
     * The meta object literal for the '<em><b>Jdbc Provider Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_SOURCE__JDBC_PROVIDER_NAME = eINSTANCE.getDataSource_JdbcProviderName();

    /**
     * The meta object literal for the '<em><b>Data Source Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_SOURCE__DATA_SOURCE_URL = eINSTANCE.getDataSource_DataSourceUrl();

    /**
     * The meta object literal for the '<em><b>Component Managed Authentication Alias</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_SOURCE__COMPONENT_MANAGED_AUTHENTICATION_ALIAS = eINSTANCE.getDataSource_ComponentManagedAuthenticationAlias();

    /**
     * The meta object literal for the '<em><b>Mapping Configuration Alias</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_SOURCE__MAPPING_CONFIGURATION_ALIAS = eINSTANCE.getDataSource_MappingConfigurationAlias();

    /**
     * The meta object literal for the '<em><b>Container Mmanaged Authentication Alias</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_SOURCE__CONTAINER_MMANAGED_AUTHENTICATION_ALIAS = eINSTANCE.getDataSource_ContainerMmanagedAuthenticationAlias();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.impl.JdbcProviderImpl <em>Jdbc Provider</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.impl.JdbcProviderImpl
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getJdbcProvider()
     * @generated
     */
    EClass JDBC_PROVIDER = eINSTANCE.getJdbcProvider();

    /**
     * The meta object literal for the '<em><b>Scope</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JDBC_PROVIDER__SCOPE = eINSTANCE.getJdbcProvider_Scope();

    /**
     * The meta object literal for the '<em><b>Database Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JDBC_PROVIDER__DATABASE_TYPE = eINSTANCE.getJdbcProvider_DatabaseType();

    /**
     * The meta object literal for the '<em><b>Provider Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JDBC_PROVIDER__PROVIDER_TYPE = eINSTANCE.getJdbcProvider_ProviderType();

    /**
     * The meta object literal for the '<em><b>Implementation Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JDBC_PROVIDER__IMPLEMENTATION_TYPE = eINSTANCE.getJdbcProvider_ImplementationType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JDBC_PROVIDER__NAME = eINSTANCE.getJdbcProvider_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JDBC_PROVIDER__DESCRIPTION = eINSTANCE.getJdbcProvider_Description();

    /**
     * The meta object literal for the '<em><b>Classpath</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JDBC_PROVIDER__CLASSPATH = eINSTANCE.getJdbcProvider_Classpath();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.impl.JAASAliasImpl <em>JAAS Alias</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.impl.JAASAliasImpl
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getJAASAlias()
     * @generated
     */
    EClass JAAS_ALIAS = eINSTANCE.getJAASAlias();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JAAS_ALIAS__ALIAS = eINSTANCE.getJAASAlias_Alias();

    /**
     * The meta object literal for the '<em><b>Username</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JAAS_ALIAS__USERNAME = eINSTANCE.getJAASAlias_Username();

    /**
     * The meta object literal for the '<em><b>Password</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JAAS_ALIAS__PASSWORD = eINSTANCE.getJAASAlias_Password();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.impl.ServerJvmSettingImpl <em>Server Jvm Setting</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.impl.ServerJvmSettingImpl
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getServerJvmSetting()
     * @generated
     */
    EClass SERVER_JVM_SETTING = eINSTANCE.getServerJvmSetting();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER_JVM_SETTING__NAME = eINSTANCE.getServerJvmSetting_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER_JVM_SETTING__VALUE = eINSTANCE.getServerJvmSetting_Value();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.SupportedContainer <em>Supported Container</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.SupportedContainer
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getSupportedContainer()
     * @generated
     */
    EEnum SUPPORTED_CONTAINER = eINSTANCE.getSupportedContainer();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.SupportedContainerOperations <em>Supported Container Operations</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.SupportedContainerOperations
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getSupportedContainerOperations()
     * @generated
     */
    EEnum SUPPORTED_CONTAINER_OPERATIONS = eINSTANCE.getSupportedContainerOperations();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.SupportedOs <em>Supported Os</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.SupportedOs
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getSupportedOs()
     * @generated
     */
    EEnum SUPPORTED_OS = eINSTANCE.getSupportedOs();

    /**
     * The meta object literal for the '{@link org.acac.demo.acdsl.myACDSL.DeploymentOp <em>Deployment Op</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.acac.demo.acdsl.myACDSL.DeploymentOp
     * @see org.acac.demo.acdsl.myACDSL.impl.MyACDSLPackageImpl#getDeploymentOp()
     * @generated
     */
    EEnum DEPLOYMENT_OP = eINSTANCE.getDeploymentOp();

  }

} //MyACDSLPackage
