/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.acac.demo.acdsl.MyACDSLRuntimeModule;
import org.acac.demo.acdsl.MyACDSLStandaloneSetup;
import org.acac.demo.acdsl.ide.MyACDSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyACDSLIdeSetup extends MyACDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyACDSLRuntimeModule _myACDSLRuntimeModule = new MyACDSLRuntimeModule();
    MyACDSLIdeModule _myACDSLIdeModule = new MyACDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_myACDSLRuntimeModule, _myACDSLIdeModule));
  }
}
