/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.ide;

import org.acac.demo.acdsl.ide.AbstractMyACDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyACDSLIdeModule extends AbstractMyACDSLIdeModule {
}
