/*
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyACDSLStandaloneSetup extends MyACDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new MyACDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
