/*
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyACDSLRuntimeModule extends AbstractMyACDSLRuntimeModule {
}
