/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.validation;

import org.acac.demo.acdsl.validation.AbstractMyACDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MyACDSLValidator extends AbstractMyACDSLValidator {
}
