/*
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyACDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/acac/demo/acdsl/parser/antlr/internal/InternalMyACDSL.tokens");
	}
}
