/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl;

import org.acac.demo.acdsl.MyACDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyACDSLStandaloneSetup extends MyACDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new MyACDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
