/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl;

import org.acac.demo.acdsl.AbstractMyACDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyACDSLRuntimeModule extends AbstractMyACDSLRuntimeModule {
}
