/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.ui;

import org.acac.demo.acdsl.ui.AbstractMyACDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MyACDSLUiModule extends AbstractMyACDSLUiModule {
  public MyACDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
