/*
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyACDSLScopeProvider extends DelegatingScopeProvider {
}
