/*
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.ui;

import com.google.inject.Injector;
import org.acac.demo.acdsl.ui.internal.AcdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyACDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AcdslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AcdslActivator.getInstance().getInjector(AcdslActivator.ORG_ACAC_DEMO_ACDSL_MYACDSL);
	}
	
}
