/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.ui.contentassist;

import org.acac.demo.acdsl.ui.contentassist.AbstractMyACDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyACDSLProposalProvider extends AbstractMyACDSLProposalProvider {
}
