/*
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class MyACDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
