/**
 * generated by Xtext 2.11.0
 */
package org.acac.demo.acdsl.myACDSL.impl;

import org.acac.demo.acdsl.myACDSL.AbstractElement;
import org.acac.demo.acdsl.myACDSL.AppServerInfo;
import org.acac.demo.acdsl.myACDSL.CommonParam;
import org.acac.demo.acdsl.myACDSL.Configuration;
import org.acac.demo.acdsl.myACDSL.ConfigurationType;
import org.acac.demo.acdsl.myACDSL.DataSource;
import org.acac.demo.acdsl.myACDSL.Deployment;
import org.acac.demo.acdsl.myACDSL.DeploymentOp;
import org.acac.demo.acdsl.myACDSL.JAASAlias;
import org.acac.demo.acdsl.myACDSL.JdbcProvider;
import org.acac.demo.acdsl.myACDSL.Model;
import org.acac.demo.acdsl.myACDSL.MyACDSLFactory;
import org.acac.demo.acdsl.myACDSL.MyACDSLPackage;
import org.acac.demo.acdsl.myACDSL.Operation;
import org.acac.demo.acdsl.myACDSL.ServerJvmSetting;
import org.acac.demo.acdsl.myACDSL.SupportedContainer;
import org.acac.demo.acdsl.myACDSL.SupportedContainerOperations;
import org.acac.demo.acdsl.myACDSL.SupportedOs;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MyACDSLPackageImpl extends EPackageImpl implements MyACDSLPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass abstractElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass configurationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass deploymentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass appServerInfoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass commonParamEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass configurationTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dataSourceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdbcProviderEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jaasAliasEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass serverJvmSettingEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum supportedContainerEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum supportedContainerOperationsEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum supportedOsEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum deploymentOpEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.acac.demo.acdsl.myACDSL.MyACDSLPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private MyACDSLPackageImpl()
  {
    super(eNS_URI, MyACDSLFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link MyACDSLPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static MyACDSLPackage init()
  {
    if (isInited) return (MyACDSLPackage)EPackage.Registry.INSTANCE.getEPackage(MyACDSLPackage.eNS_URI);

    // Obtain or create and register package
    MyACDSLPackageImpl theMyACDSLPackage = (MyACDSLPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof MyACDSLPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new MyACDSLPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theMyACDSLPackage.createPackageContents();

    // Initialize created meta-data
    theMyACDSLPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theMyACDSLPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(MyACDSLPackage.eNS_URI, theMyACDSLPackage);
    return theMyACDSLPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Elements()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAbstractElement()
  {
    return abstractElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getConfiguration()
  {
    return configurationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getConfiguration_AppName()
  {
    return (EAttribute)configurationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getConfiguration_Os()
  {
    return (EAttribute)configurationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getConfiguration_AppServer()
  {
    return (EReference)configurationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getConfiguration_CommonParams()
  {
    return (EReference)configurationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getConfiguration_Configurations()
  {
    return (EReference)configurationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDeployment()
  {
    return deploymentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDeployment_AppOp()
  {
    return (EAttribute)deploymentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getOperation()
  {
    return operationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getOperation_ServerOp()
  {
    return (EAttribute)operationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAppServerInfo()
  {
    return appServerInfoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAppServerInfo_Name()
  {
    return (EAttribute)appServerInfoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAppServerInfo_Version()
  {
    return (EAttribute)appServerInfoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCommonParam()
  {
    return commonParamEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCommonParam_Name()
  {
    return (EAttribute)commonParamEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCommonParam_Value()
  {
    return (EAttribute)commonParamEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getConfigurationType()
  {
    return configurationTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDataSource()
  {
    return dataSourceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDataSource_Scope()
  {
    return (EReference)dataSourceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDataSource_DataSourceName()
  {
    return (EAttribute)dataSourceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDataSource_JndiName()
  {
    return (EAttribute)dataSourceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDataSource_JdbcProviderName()
  {
    return (EAttribute)dataSourceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDataSource_DataSourceUrl()
  {
    return (EAttribute)dataSourceEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDataSource_ComponentManagedAuthenticationAlias()
  {
    return (EReference)dataSourceEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDataSource_MappingConfigurationAlias()
  {
    return (EReference)dataSourceEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDataSource_ContainerMmanagedAuthenticationAlias()
  {
    return (EReference)dataSourceEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdbcProvider()
  {
    return jdbcProviderEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdbcProvider_Scope()
  {
    return (EReference)jdbcProviderEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdbcProvider_DatabaseType()
  {
    return (EAttribute)jdbcProviderEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdbcProvider_ProviderType()
  {
    return (EAttribute)jdbcProviderEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdbcProvider_ImplementationType()
  {
    return (EAttribute)jdbcProviderEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdbcProvider_Name()
  {
    return (EAttribute)jdbcProviderEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdbcProvider_Description()
  {
    return (EAttribute)jdbcProviderEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdbcProvider_Classpath()
  {
    return (EReference)jdbcProviderEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJAASAlias()
  {
    return jaasAliasEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJAASAlias_Alias()
  {
    return (EReference)jaasAliasEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJAASAlias_Username()
  {
    return (EAttribute)jaasAliasEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJAASAlias_Password()
  {
    return (EAttribute)jaasAliasEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getServerJvmSetting()
  {
    return serverJvmSettingEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getServerJvmSetting_Name()
  {
    return (EAttribute)serverJvmSettingEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getServerJvmSetting_Value()
  {
    return (EAttribute)serverJvmSettingEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getSupportedContainer()
  {
    return supportedContainerEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getSupportedContainerOperations()
  {
    return supportedContainerOperationsEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getSupportedOs()
  {
    return supportedOsEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getDeploymentOp()
  {
    return deploymentOpEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MyACDSLFactory getMyACDSLFactory()
  {
    return (MyACDSLFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__ELEMENTS);

    abstractElementEClass = createEClass(ABSTRACT_ELEMENT);

    configurationEClass = createEClass(CONFIGURATION);
    createEAttribute(configurationEClass, CONFIGURATION__APP_NAME);
    createEAttribute(configurationEClass, CONFIGURATION__OS);
    createEReference(configurationEClass, CONFIGURATION__APP_SERVER);
    createEReference(configurationEClass, CONFIGURATION__COMMON_PARAMS);
    createEReference(configurationEClass, CONFIGURATION__CONFIGURATIONS);

    deploymentEClass = createEClass(DEPLOYMENT);
    createEAttribute(deploymentEClass, DEPLOYMENT__APP_OP);

    operationEClass = createEClass(OPERATION);
    createEAttribute(operationEClass, OPERATION__SERVER_OP);

    appServerInfoEClass = createEClass(APP_SERVER_INFO);
    createEAttribute(appServerInfoEClass, APP_SERVER_INFO__NAME);
    createEAttribute(appServerInfoEClass, APP_SERVER_INFO__VERSION);

    commonParamEClass = createEClass(COMMON_PARAM);
    createEAttribute(commonParamEClass, COMMON_PARAM__NAME);
    createEAttribute(commonParamEClass, COMMON_PARAM__VALUE);

    configurationTypeEClass = createEClass(CONFIGURATION_TYPE);

    dataSourceEClass = createEClass(DATA_SOURCE);
    createEReference(dataSourceEClass, DATA_SOURCE__SCOPE);
    createEAttribute(dataSourceEClass, DATA_SOURCE__DATA_SOURCE_NAME);
    createEAttribute(dataSourceEClass, DATA_SOURCE__JNDI_NAME);
    createEAttribute(dataSourceEClass, DATA_SOURCE__JDBC_PROVIDER_NAME);
    createEAttribute(dataSourceEClass, DATA_SOURCE__DATA_SOURCE_URL);
    createEReference(dataSourceEClass, DATA_SOURCE__COMPONENT_MANAGED_AUTHENTICATION_ALIAS);
    createEReference(dataSourceEClass, DATA_SOURCE__MAPPING_CONFIGURATION_ALIAS);
    createEReference(dataSourceEClass, DATA_SOURCE__CONTAINER_MMANAGED_AUTHENTICATION_ALIAS);

    jdbcProviderEClass = createEClass(JDBC_PROVIDER);
    createEReference(jdbcProviderEClass, JDBC_PROVIDER__SCOPE);
    createEAttribute(jdbcProviderEClass, JDBC_PROVIDER__DATABASE_TYPE);
    createEAttribute(jdbcProviderEClass, JDBC_PROVIDER__PROVIDER_TYPE);
    createEAttribute(jdbcProviderEClass, JDBC_PROVIDER__IMPLEMENTATION_TYPE);
    createEAttribute(jdbcProviderEClass, JDBC_PROVIDER__NAME);
    createEAttribute(jdbcProviderEClass, JDBC_PROVIDER__DESCRIPTION);
    createEReference(jdbcProviderEClass, JDBC_PROVIDER__CLASSPATH);

    jaasAliasEClass = createEClass(JAAS_ALIAS);
    createEReference(jaasAliasEClass, JAAS_ALIAS__ALIAS);
    createEAttribute(jaasAliasEClass, JAAS_ALIAS__USERNAME);
    createEAttribute(jaasAliasEClass, JAAS_ALIAS__PASSWORD);

    serverJvmSettingEClass = createEClass(SERVER_JVM_SETTING);
    createEAttribute(serverJvmSettingEClass, SERVER_JVM_SETTING__NAME);
    createEAttribute(serverJvmSettingEClass, SERVER_JVM_SETTING__VALUE);

    // Create enums
    supportedContainerEEnum = createEEnum(SUPPORTED_CONTAINER);
    supportedContainerOperationsEEnum = createEEnum(SUPPORTED_CONTAINER_OPERATIONS);
    supportedOsEEnum = createEEnum(SUPPORTED_OS);
    deploymentOpEEnum = createEEnum(DEPLOYMENT_OP);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    configurationEClass.getESuperTypes().add(this.getAbstractElement());
    deploymentEClass.getESuperTypes().add(this.getAbstractElement());
    operationEClass.getESuperTypes().add(this.getAbstractElement());
    dataSourceEClass.getESuperTypes().add(this.getConfigurationType());
    jdbcProviderEClass.getESuperTypes().add(this.getConfigurationType());
    jaasAliasEClass.getESuperTypes().add(this.getConfigurationType());
    serverJvmSettingEClass.getESuperTypes().add(this.getConfigurationType());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Elements(), this.getAbstractElement(), null, "elements", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(abstractElementEClass, AbstractElement.class, "AbstractElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(configurationEClass, Configuration.class, "Configuration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConfiguration_AppName(), ecorePackage.getEString(), "appName", null, 0, 1, Configuration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getConfiguration_Os(), this.getSupportedOs(), "os", null, 0, 1, Configuration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConfiguration_AppServer(), this.getAppServerInfo(), null, "appServer", null, 0, 1, Configuration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConfiguration_CommonParams(), this.getCommonParam(), null, "commonParams", null, 0, -1, Configuration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConfiguration_Configurations(), this.getConfigurationType(), null, "configurations", null, 0, -1, Configuration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(deploymentEClass, Deployment.class, "Deployment", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDeployment_AppOp(), this.getDeploymentOp(), "appOp", null, 0, -1, Deployment.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operationEClass, Operation.class, "Operation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOperation_ServerOp(), this.getSupportedContainerOperations(), "serverOp", null, 0, -1, Operation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(appServerInfoEClass, AppServerInfo.class, "AppServerInfo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAppServerInfo_Name(), this.getSupportedContainer(), "name", null, 0, 1, AppServerInfo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAppServerInfo_Version(), ecorePackage.getEString(), "version", null, 0, 1, AppServerInfo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(commonParamEClass, CommonParam.class, "CommonParam", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCommonParam_Name(), ecorePackage.getEString(), "name", null, 0, 1, CommonParam.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCommonParam_Value(), ecorePackage.getEString(), "value", null, 0, 1, CommonParam.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(configurationTypeEClass, ConfigurationType.class, "ConfigurationType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(dataSourceEClass, DataSource.class, "DataSource", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDataSource_Scope(), this.getCommonParam(), null, "scope", null, 0, 1, DataSource.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDataSource_DataSourceName(), ecorePackage.getEString(), "dataSourceName", null, 0, 1, DataSource.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDataSource_JndiName(), ecorePackage.getEString(), "jndiName", null, 0, 1, DataSource.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDataSource_JdbcProviderName(), ecorePackage.getEString(), "jdbcProviderName", null, 0, 1, DataSource.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDataSource_DataSourceUrl(), ecorePackage.getEString(), "dataSourceUrl", null, 0, 1, DataSource.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDataSource_ComponentManagedAuthenticationAlias(), this.getCommonParam(), null, "componentManagedAuthenticationAlias", null, 0, 1, DataSource.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDataSource_MappingConfigurationAlias(), this.getCommonParam(), null, "mappingConfigurationAlias", null, 0, 1, DataSource.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDataSource_ContainerMmanagedAuthenticationAlias(), this.getCommonParam(), null, "containerMmanagedAuthenticationAlias", null, 0, 1, DataSource.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdbcProviderEClass, JdbcProvider.class, "JdbcProvider", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJdbcProvider_Scope(), this.getCommonParam(), null, "scope", null, 0, 1, JdbcProvider.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdbcProvider_DatabaseType(), ecorePackage.getEString(), "databaseType", null, 0, 1, JdbcProvider.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdbcProvider_ProviderType(), ecorePackage.getEString(), "providerType", null, 0, 1, JdbcProvider.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdbcProvider_ImplementationType(), ecorePackage.getEString(), "implementationType", null, 0, 1, JdbcProvider.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdbcProvider_Name(), ecorePackage.getEString(), "name", null, 0, 1, JdbcProvider.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdbcProvider_Description(), ecorePackage.getEString(), "description", null, 0, 1, JdbcProvider.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdbcProvider_Classpath(), this.getCommonParam(), null, "classpath", null, 0, 1, JdbcProvider.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jaasAliasEClass, JAASAlias.class, "JAASAlias", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJAASAlias_Alias(), this.getCommonParam(), null, "alias", null, 0, 1, JAASAlias.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJAASAlias_Username(), ecorePackage.getEString(), "username", null, 0, 1, JAASAlias.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJAASAlias_Password(), ecorePackage.getEString(), "password", null, 0, 1, JAASAlias.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(serverJvmSettingEClass, ServerJvmSetting.class, "ServerJvmSetting", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getServerJvmSetting_Name(), ecorePackage.getEString(), "name", null, 0, 1, ServerJvmSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getServerJvmSetting_Value(), ecorePackage.getEString(), "value", null, 0, 1, ServerJvmSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(supportedContainerEEnum, SupportedContainer.class, "SupportedContainer");
    addEEnumLiteral(supportedContainerEEnum, SupportedContainer.WEB_SPHERE);
    addEEnumLiteral(supportedContainerEEnum, SupportedContainer.TOMCAT);

    initEEnum(supportedContainerOperationsEEnum, SupportedContainerOperations.class, "SupportedContainerOperations");
    addEEnumLiteral(supportedContainerOperationsEEnum, SupportedContainerOperations.STOP);
    addEEnumLiteral(supportedContainerOperationsEEnum, SupportedContainerOperations.START);
    addEEnumLiteral(supportedContainerOperationsEEnum, SupportedContainerOperations.RESTART);

    initEEnum(supportedOsEEnum, SupportedOs.class, "SupportedOs");
    addEEnumLiteral(supportedOsEEnum, SupportedOs.LINUX);
    addEEnumLiteral(supportedOsEEnum, SupportedOs.WIN);
    addEEnumLiteral(supportedOsEEnum, SupportedOs.AIX);

    initEEnum(deploymentOpEEnum, DeploymentOp.class, "DeploymentOp");
    addEEnumLiteral(deploymentOpEEnum, DeploymentOp.UNINSTALL);
    addEEnumLiteral(deploymentOpEEnum, DeploymentOp.INSTALL);
    addEEnumLiteral(deploymentOpEEnum, DeploymentOp.UPDATE);

    // Create resource
    createResource(eNS_URI);
  }

} //MyACDSLPackageImpl
